import type { Channel, WorkProductId, WorkRecord } from "./types";
import { HARBOR, RIVERSIDE } from "./seed";

function item(
  id: string,
  shopId: string,
  productId: WorkProductId,
  title: string,
  opts: {
    detail: string;
    evidence: string;
    source: string;
    amount: number;
    ownerName: string;
    channel: Channel;
    classification?: string | null;
    subject: string;
    body: string;
    done?: boolean;
  },
): WorkRecord {
  return {
    id,
    shopId,
    productId,
    title,
    detail: opts.detail,
    evidence: opts.evidence,
    source: opts.source,
    amount: opts.amount,
    ownerName: opts.ownerName,
    channel: opts.channel,
    classification: opts.classification ?? null,
    subject: opts.subject,
    body: opts.body,
    done: opts.done ?? false,
  };
}

const DANA = "Dana Ruiz";
const MIKE = "Mike Chen";
const LUIS = "Luis Ortega";
const sign = `${DANA}\nNorthline Supply`;

export const works: WorkRecord[] = [
  item("w_ah_1", RIVERSIDE, "afterhours", "West Shore Authority · overnight call", {
    detail: "Missed at 21:14. Classified as a meeting request.",
    evidence: "Overnight inbound. Classified as meeting. Number 717-555-0202. Owner Dana Ruiz. Held for morning.",
    source: "717-555-0202",
    amount: 6400,
    ownerName: DANA,
    channel: "sms",
    classification: "meeting",
    subject: "Text 717-555-0202",
    body: "Northline Supply. We got your call after hours. This is Dana. I am in now. If you still need a meeting today, reply with a morning or afternoon.",
  }),
  item("w_ah_2", RIVERSIDE, "afterhours", "Jordan Lee · overnight chat", {
    detail: "Chat at 21:40. Classified as a scheduling question.",
    evidence: "Overnight chat. Classified as question. Asked: Can someone confirm a Tuesday morning. Owner Dana Ruiz. Held for morning.",
    source: "chat",
    amount: 2800,
    ownerName: DANA,
    channel: "chat",
    classification: "question",
    subject: "Chat with Jordan Lee",
    body: "Hi Jordan, this is Dana at Northline Supply. You wrote after hours. You asked: Can someone confirm a Tuesday morning. I can hold it. Reply here.",
  }),
  item("w_ah_3", RIVERSIDE, "afterhours", "Cumberland Water · overnight form", {
    detail: "Form at 20:05. Classified as other. Parts question.",
    evidence: "Overnight web form. Classified as other. Asked: What is lead time on the spare kit for plant 2. Email c.nguyen@cumberlandwater.example. Owner Mike Chen. Held for morning.",
    source: "c.nguyen@cumberlandwater.example",
    amount: 8900,
    ownerName: MIKE,
    channel: "email",
    classification: "other",
    subject: "Your note to Northline Supply",
    body: `Hi Chris,\n\nThis is Mike at Northline Supply. We received your form after hours. You asked about lead time on the spare kit for plant 2. I can confirm stock this morning. Reply with a time if you want a call.\n\nMike Chen\nNorthline Supply`,
  }),
  item("w_rev_1", RIVERSIDE, "reviews", "Lab services · ask for a note", {
    detail: "Work completed. No testimonial request sent.",
    evidence: "Opp OPP-45044 completed 4 days ago. Ticket 16000. No review request. Owner Dana Ruiz.",
    source: "OPP-45044",
    amount: 16000,
    ownerName: DANA,
    channel: "email",
    subject: "Would you mind a short note",
    body: `Hi Jordan,\n\nThis is Dana at Northline Supply. Thanks for the work last week. If it went the way it should have, a short note I can show the next buyer helps more than you would think. I will not send this unless you are happy to.\n\n${sign}`,
  }),
  item("w_pres_1", RIVERSIDE, "presence", "Google profile · hours mismatch", {
    detail: "Public hours still say Saturday 8 to 12. Desk closed that window in March.",
    evidence: "Profile diff, 2 days ago. Ranking for controls contractor Harrisburg slipped 3 to 6. Post drafted, not published.",
    source: "gbp",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Profile correction",
    body: "Correction: Saturday hours should read closed. Draft post: This week we are on-site at two school districts for building automation walkthroughs. Reply to book a walkthrough.",
  }),
  item("w_res_1", RIVERSIDE, "resource", "April note · what operations teams changed", {
    detail: "Monthly giveaway. Distribution list of 40 quiet accounts.",
    evidence: "Asset drafted from Q1 call themes. 40 contacts, last useful letter 18 days ago or more.",
    source: "resource-apr",
    amount: 0,
    ownerName: DANA,
    channel: "email",
    subject: "Something useful, no ask",
    body: `Hi there,\n\nThis is Dana at Northline Supply. I am not asking for a meeting. I attached a short note on what operations teams in your spot changed this quarter. If it is useful, keep it. If not, tell me to stop.\n\n${sign}`,
  }),
  item("w_route_1", RIVERSIDE, "routing", "Reassign · Dana over capacity", {
    detail: "Dana has 11 waiting. Mike has 2. Territory rule would move Capital Region Schools.",
    evidence: "Capacity rule: 8 open drafts. Dana at 11. Proposed owner Mike Chen. Reason: same county, open calendar Tuesday.",
    source: "route-1",
    amount: 12400,
    ownerName: MIKE,
    channel: "none",
    subject: "Routing proposal",
    body: "Move Capital Region Schools from Dana Ruiz to Mike Chen. Dana is over the 8-draft cap. Mike owns the adjacent territory and has Tuesday morning open.",
  }),
  item("w_sweep_1", RIVERSIDE, "sweep", "Meridian Labs · 9 days, no touch", {
    detail: "Inbound lead, no activity since create.",
    evidence: "Created 9 days ago. Owner Unassigned. Estimated 9600. Source: press release, state lab-expansion grant.",
    source: "lead-meridian",
    amount: 9600,
    ownerName: DANA,
    channel: "email",
    subject: "Saw this about Meridian Labs",
    body: `Hi there,\n\nThis is Dana at Northline Supply. I saw that Meridian Labs won a state lab-expansion grant. We help operations teams with the controls and instrumentation side of that work. If a short call this week is useful, reply with a morning or afternoon.\n\n${sign}`,
  }),
  item("w_fit_1", RIVERSIDE, "fit", "Avery Cole · fit 86", {
    detail: "Matches the onboarding definition of a good fit.",
    evidence: "Fit 86. Public buyer, two campuses, dated bid, inside the 90-day runway. Reject rule does not fire. Owner Dana Ruiz.",
    source: "enq_1",
    amount: 12400,
    ownerName: DANA,
    channel: "none",
    classification: "fit 86",
    subject: "Fit score",
    body: "Keep. Public buyer, two campuses, dated reason to buy. Score 86 against the interview definition. Route stays with Dana.",
  }),
  item("w_seq_1", RIVERSIDE, "sequences", "Buying-cue sequence · install", {
    detail: "One sequence per signal type, in Dana's voice.",
    evidence: "Signal types: public bid, capital plan, job post. Three notes, day 0, 3, and 7. Voice v2. Not installed.",
    source: "seq-cue",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Sequence pack",
    body: "Buying-cue sequence for Northline.\nDay 0: name the public source, no ask.\nDay 3: one useful note from similar work.\nDay 7: ask for a morning or afternoon.\nVoice: Dana v2. Install in the CRM after you approve. Dry-run.",
  }),
  item("w_qd_1", RIVERSIDE, "quotedraft", "Cumberland Water · flow meter estimate", {
    detail: "Notes plus price book. Held for Dana.",
    evidence: "Field notes: plant 2, four lines, existing 4-inch meters. Price book line FM-4 2200 each, install 1200. Total 8900.",
    source: "est-cw-2",
    amount: 8900,
    ownerName: DANA,
    channel: "none",
    subject: "Estimate, Cumberland Water plant 2",
    body: "Northline Supply estimate\nCumberland Water, plant 2\nFlow meter replacement, four lines\nEquipment 8,800\nInstall 1,200\nTotal 8,900\nLead time 12 days\nValid 14 days\nDana Ruiz",
  }),
  item("w_fq_1", RIVERSIDE, "fieldquote", "Plant 4 · spare VFD kit from the floor", {
    detail: "Tech note before they left the site.",
    evidence: "Photo note: spare VFD kit, same as last year. Price book VFD-SP 3800. Owner Dana Ruiz.",
    source: "field-p4",
    amount: 3800,
    ownerName: DANA,
    channel: "none",
    subject: "Quote from the floor, Plant 4",
    body: "Northline Supply estimate\nPlant 4, spare VFD kit\nSame specification as last year\nTotal 3,800\nCan ship this week\nDana Ruiz",
  }),
  item("w_rfp_1", RIVERSIDE, "rfp", "Westfield ISD · bid packet due in 11 days", {
    detail: "Library match 7 of 9 required answers. Two gaps.",
    evidence: "Due in 11 days. Missing: insurance certificate current, three references in K-12. Prior answers cover scope, warranty, staffing.",
    source: "rfp-westfield",
    amount: 42000,
    ownerName: MIKE,
    channel: "none",
    subject: "RFP gap list",
    body: "Westfield ISD building automation bid\nDue in 11 days\nCovered: scope, warranty, staffing, safety, pricing format, change order, insurance types\nGaps: current certificate of insurance, three K-12 references\nAssign certificate to Mike. Assign references to Dana.",
  }),
  item("w_obj_1", RIVERSIDE, "objections", "This quarter · we already have a vendor", {
    detail: "Heard 6 times. The answer that won twice is attached.",
    evidence: "Dana 4, Mike 2. Won after: we are not asking you to rip them out. We are the spare and the second source when they miss a lead time.",
    source: "obj-vendor",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Objection map",
    body: "Objection: we already have a vendor.\nAnswer that won: we are not asking you to rip them out. We are the spare and the second source when they miss a lead time.\nDo not say cheaper. Do not say guaranteed. Refresh next quarter.",
  }),
  item("w_dis_1", RIVERSIDE, "displace", "Harrisburg Housing Authority · incumbent renews in 40 days", {
    detail: "Original buying cue still attached.",
    evidence: "Contract note: incumbent calibration vendor renews in 40 days. Original cue: capital plan names HVAC controls for 2026. Amount 31000.",
    source: "cue_4",
    amount: 31000,
    ownerName: DANA,
    channel: "email",
    subject: "Before your renewal window closes",
    body: `Hi there,\n\nThis is Dana at Northline Supply. Your current calibration vendor comes up for renewal in about 40 days. The capital plan still names HVAC controls for 2026. If a second look is useful before you sign, reply with a morning or afternoon.\n\n${sign}`,
  }),
  item("w_mc_1", RIVERSIDE, "meetingcrm", "Westfield ISD · notes from Tuesday", {
    detail: "Proposed next step and stage change. Dana confirms.",
    evidence: "Call Tuesday. Next step missing in CRM. Proposed: stage to Proposal, next meeting Friday 10:00, note attached.",
    source: "call-westfield-tues",
    amount: 42000,
    ownerName: DANA,
    channel: "none",
    subject: "CRM write-back, dry-run",
    body: "Account: Westfield ISD\nNote: Walked three campuses. They want a phased bid, not a single lump. Decision maker is facilities, not the superintendent.\nNext: Friday 10:00, send draft scope Wednesday.\nStage: Proposal\nNothing writes until you approve.",
  }),
  item("w_br_1", RIVERSIDE, "brief", "Friday 10:00 · Westfield ISD", {
    detail: "One page. CRM, last call, the bid notice.",
    evidence: "Meeting Friday 10:00. Last call Tuesday. Public bid still open. Open proposal none. Owner Dana Ruiz.",
    source: "brief-westfield",
    amount: 42000,
    ownerName: DANA,
    channel: "none",
    subject: "Brief, Friday 10:00",
    body: "Westfield ISD, Friday 10:00\nThey posted a bid for building automation on three campuses.\nLast conversation: phased bid, facilities signs.\nOpen items: draft scope due Wednesday.\nDo not reopen price. Ask who else has to see the draft.",
  }),
  item("w_ob_1", RIVERSIDE, "onboard", "Lab services · day 7 check-in", {
    detail: "New customer, first thirty days. Day 7 touch.",
    evidence: "Won 7 days ago. Calibration contract 16000. No check-in sent. Sequence: day 1, 7, 21, 30.",
    source: "onboard-lab",
    amount: 16000,
    ownerName: DANA,
    channel: "email",
    subject: "How the first week went",
    body: `Hi Jordan,\n\nThis is Dana at Northline Supply. You have had a week with the calibration contract. If anything is off, reply here and I will fix it. If it is fine, no need to do anything.\n\n${sign}`,
  }),
  item("w_js_1", RIVERSIDE, "jobstatus", "Plant 2 · spare kit shipped", {
    detail: "Status changed to shipped. Customer has not been told.",
    evidence: "Opp OPP-45018. Status shipped this morning. Tracking on file. Owner Dana Ruiz.",
    source: "OPP-45018",
    amount: 3800,
    ownerName: DANA,
    channel: "email",
    subject: "Your spare kit is on the way",
    body: `Hi Pat,\n\nThis is Dana at Northline Supply. The spare controls kit for Plant 2 shipped this morning. If you want the tracking number on this thread, reply yes.\n\n${sign}`,
  }),
  item("w_wa_1", RIVERSIDE, "warranty", "Facilities · 90-day check-in", {
    detail: "Warranty window. Maintenance visit not booked.",
    evidence: "VFD retrofit completed 88 days ago. Warranty 90 days. No visit on the book. Owner Dana Ruiz.",
    source: "OPP-45001",
    amount: 4200,
    ownerName: DANA,
    channel: "email",
    subject: "Ninety-day check-in",
    body: `Hi Riley,\n\nThis is Dana at Northline Supply. The VFD retrofit is coming up on ninety days. If you want a walkthrough while it is still under warranty, reply with a morning or afternoon.\n\n${sign}`,
  }),
  item("w_dun_1", RIVERSIDE, "dunning", "Expired card · retry blocked", {
    detail: "Card on file expires in 9 days. Last failure was expired_card.",
    evidence: "Payment failed, reason expired_card. Not retried. Ask for a new card. Do not auto-retry.",
    source: "pay_expired",
    amount: 2100,
    ownerName: DANA,
    channel: "email",
    subject: "A charge did not go through",
    body: `Hi there,\n\nThis is Dana at Northline Supply. A charge did not go through because the card on file is expired. Reply with a card we can use, or a date to try again, and I will take care of it.\n\n${sign}`,
  }),
  item("w_pp_1", RIVERSIDE, "payplan", "Invoice past 60 · offer terms", {
    detail: "Balance above the threshold. Offer three payments.",
    evidence: "Invoice aging 61 days. Balance 4800. Threshold 2500. Customer history: paid the last three on time before this one.",
    source: "inv-60",
    amount: 4800,
    ownerName: DANA,
    channel: "email",
    subject: "A plan for the open invoice",
    body: `Hi there,\n\nThis is Dana at Northline Supply. Invoice balance 4,800 is past 60 days. If three payments over 45 days would close it, reply yes and I will send the dates. If you already paid, reply with the confirmation.\n\n${sign}`,
  }),
  item("w_dep_1", RIVERSIDE, "deposit", "Westfield walkthrough · deposit not in", {
    detail: "Job cannot start. Deposit still open.",
    evidence: "Scheduled start in 8 days. Deposit 20 percent, 8400, not received. Job-start flag blocked.",
    source: "dep-westfield",
    amount: 8400,
    ownerName: DANA,
    channel: "email",
    subject: "Deposit before we start",
    body: `Hi there,\n\nThis is Dana at Northline Supply. The walkthrough is on the book in eight days. The deposit is still open. Reply with a card or a date and I will confirm the start.\n\n${sign}`,
  }),
  item("w_sb_1", RIVERSIDE, "secondbook", "Plant 4 · rebook before they leave", {
    detail: "Walkthrough just finished. No next meeting on the book.",
    evidence: "Appointment completed this morning. Ticket 3,800. Next on: none. The tech is still on site. Number 717-555-0144. Owner Dana Ruiz.",
    source: "appt-p4-done",
    amount: 3800,
    ownerName: DANA,
    channel: "sms",
    classification: "rebook",
    subject: "Text Plant 4",
    body: "Northline Supply. This is Dana. While we are still on site, I can put the spare kit follow-up on the book. Reply with a morning next week.",
  }),
  item("w_wl_1", RIVERSIDE, "waitlist", "Thursday 14:00 opened", {
    detail: "Cancellation. Waitlist of 3. First is Lab services.",
    evidence: "Slot Thursday 14:00 cancelled 11 minutes ago. Waitlist: Lab services, Plant 4, Facilities. Offer in that order. Number 717-555-0188. Owner Dana Ruiz.",
    source: "slot-thu-1400",
    amount: 1600,
    ownerName: DANA,
    channel: "sms",
    classification: "waitlist",
    subject: "Text Lab services",
    body: "Northline Supply. This is Dana. A Thursday 2:00 opened. If you still want it, reply YES and I will hold it for 20 minutes.",
  }),
  item("w_ns_1", RIVERSIDE, "noshow", "Plant 4 · reminder for tomorrow", {
    detail: "This account missed once in the last four visits.",
    evidence: "Appointment tomorrow 9:30. No-show history 1 of 4. Reminder not sent. Confirmation required. Number 717-555-0166. Owner Dana Ruiz.",
    source: "appt-p4",
    amount: 3800,
    ownerName: DANA,
    channel: "sms",
    subject: "Text Plant 4",
    body: "Northline Supply. This is Dana. Confirming tomorrow at 9:30 for the spare kit. Reply YES to keep it, or send another morning.",
  }),
  item("w_mr_1", RIVERSIDE, "memretain", "Calibration retainer · usage dropped", {
    detail: "Usage this quarter is 40 percent of last. Renewal in 21 days.",
    evidence: "Plan: calibration retainer. Usage 2 visits vs 5 last quarter. Renews in 21 days. Not confirmed.",
    source: "mem-lab",
    amount: 14400,
    ownerName: DANA,
    channel: "email",
    subject: "Your retainer is up for renewal",
    body: `Hi Jordan,\n\nThis is Dana at Northline Supply. Your calibration retainer is due to renew. Usage is down this quarter. If you want to keep it, reply yes and I will run the card on file. If you want to pause, say so and I will stop.\n\n${sign}`,
  }),
  item("w_rf_1", RIVERSIDE, "referral", "Pat Okonkwo · quiet 11 months", {
    detail: "Sent two accounts last year. None this year.",
    evidence: "Referral source: Pat Okonkwo, Plant 2. Last referral 11 months ago. Two prior, both became jobs.",
    source: "ref-pat",
    amount: 0,
    ownerName: DANA,
    channel: "email",
    subject: "Something useful, no ask",
    body: `Hi Pat,\n\nThis is Dana at Northline Supply. I am not asking for a name. I attached the same short note I am sending operations teams this month. If someone on your side would want it, you can pass it. If not, tell me to stop.\n\n${sign}`,
  }),
  item("w_pa_1", RIVERSIDE, "partner", "HVAC adjacent · quarterly touch", {
    detail: "Partner agreement, no touch in 90 days.",
    evidence: "Partner: Capital HVAC. Agreement: 8 percent on referred jobs. Last touch 94 days. No payouts this quarter.",
    source: "partner-hvac",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Partner touch",
    body: "Capital HVAC quarterly touch. Last referred job 7 months ago. Draft: share the school-district walkthrough calendar. No payout due. Owner Mike Chen.",
  }),
  item("w_te_1", RIVERSIDE, "testimonial", "Riley Brooks · ask while it is warm", {
    detail: "Job completed, customer happy on the call. Permission not recorded.",
    evidence: "Opp OPP-45001 completed. Call classified as delight. No permission row. No quote captured.",
    source: "OPP-45001",
    amount: 4200,
    ownerName: DANA,
    channel: "email",
    subject: "Would you mind a short note",
    body: `Hi Riley,\n\nThis is Dana at Northline Supply. If last week's work went the way it should have, a short sentence I can show the next buyer helps. Reply with a line, or tell me no, and I will leave it.\n\n${sign}`,
  }),
  item("w_en_1", RIVERSIDE, "enablement", "Dana · hours on follow-up, week 3", {
    detail: "Before: 6.4 hours. This week: 4.1. Automations installed: missed-call, intake.",
    evidence: "Measurement snapshot. Follow-up hours 6.4 to 4.1. Queue still human-approved. Next install: after-hours.",
    source: "enable-dana",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Enablement delta",
    body: "Dana Ruiz, week 3 of enablement. Hours on follow-up 6.4 down to 4.1. Missed-call and form/chat are on. After-hours is next. Nothing sends itself.",
  }),
  item("w_cc_1", RIVERSIDE, "coldcall", "Sam Okonkwo · certification not passed", {
    detail: "Mock call 2 of 3. Missed the one-question discovery.",
    evidence: "Rubric: opener pass, note card pass, discovery fail, objections pass. Retake scheduled.",
    source: "cert-sam",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Certification note",
    body: "Sam Okonkwo, cold-call cert. Fail on one-question discovery. The question to use: what would have to be true for this to be worth a meeting this month. Retake Friday.",
  }),
  item("w_sc_1", RIVERSIDE, "scoring", "Dana · this week, one note", {
    detail: "Scored against the leader's rubric. One thing to repeat.",
    evidence: "Recording Thursday. Ask-for-the-meeting: yes. Next step on the book: no. Score 3 of 5.",
    source: "score-dana-w",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Weekly coaching note",
    body: "Dana Ruiz, this week. Repeat: you asked for the meeting in the first four minutes. Fix: no next step landed on the book. One thing: before you hang up, say the day and wait.",
  }),
  item("w_hi_1", RIVERSIDE, "hiring", "SDR seat · pack ready", {
    detail: "Scorecard, take-home, rubric, onboarding kit with Northline terms.",
    evidence: "Role: SDR. Terminology from the interview. Quiz attached. Owner Mike Chen.",
    source: "hire-sdr",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Hiring pack",
    body: "SDR hiring pack for Northline. Scorecard: hunting, writing, coachability. Take-home: draft a first note from a public bid. Interview rubric included. Onboarding kit uses opp, not RO, and meeting, not visit.",
  }),
  item("w_ho_1", RIVERSIDE, "handoff", "Mike's calls · first-rep package", {
    detail: "Founder calls from Q4 turned into playbook pages.",
    evidence: "12 calls, 4 wins. Sequences: buying cue, quiet proposal, missed inbound. Objection map attached.",
    source: "handoff-mike",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Founder package",
    body: "Mike Chen Q4 calls. Playbook pages: how he opens a bid, how he handles we already have a vendor, how he asks for the next meeting. Sequences ready for Dana. Nothing live until you approve.",
  }),
  item("w_cp_1", RIVERSIDE, "comp", "Plan v2 · 50/50 plus a cap", {
    detail: "Current plan is 70/30. Model attached.",
    evidence: "Quota 78k. Current 70 base / 30 variable. Proposed 50/50 with a monthly variable cap. Workshop notes in the body.",
    source: "comp-v2",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Compensation model",
    body: "Northline comp v2. Keep a cap on the variable so a good month does not feel like a punishment the next. 50 base / 50 variable, monthly cap at 1.4x. No pure performance pricing.",
  }),
  item("w_rp_1", RIVERSIDE, "roleplay", "Dana · practice the vendor objection", {
    detail: "Bot trained on this quarter's objections.",
    evidence: "Prompt: we already have a vendor. Dana last scored 2 of 4 on this. Session not started.",
    source: "roleplay-dana",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Practice session",
    body: "Role-play: buyer says we already have a vendor. Use the answer that won. Do not say cheaper. Stop when you have asked for a time. Score on ask, evidence, and no banned words.",
  }),
  item("w_tr_1", RIVERSIDE, "training", "Course · Dana's Tuesday call", {
    detail: "Best-performer call turned into SOP.",
    evidence: "Recording Tuesday, Westfield. Outcome: next meeting booked. SOP drafted from the transcript.",
    source: "train-westfield",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "New-hire course draft",
    body: "SOP: first meeting on a public bid.\n1. Name the source.\n2. Ask who signs.\n3. Put a day on the book before you hang up.\nBuilt from Dana's Tuesday Westfield call. Approve to add to the kit.",
  }),
  item("w_oo_1", RIVERSIDE, "oneonone", "Dana · Friday 1:1", {
    detail: "Last week's assignment and this week's queue.",
    evidence: "Last week: put a next step on every live deal. This week: 4 missed-call texts still open, 1 chat past 5 minutes.",
    source: "1on1-dana",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "1:1 prep",
    body: "Dana, Friday.\nLast week assignment: next step on every live deal. Two still missing.\nThis week: four missed-call texts, one chat past the window.\nAsk: what would make the chat a same-day send.",
  }),
  item("w_ro_1", RIVERSIDE, "revops", "Monday standing · records and routing", {
    detail: "Hygiene, routing, and pacing in one pack. Prepared before the meeting.",
    evidence: "14 orphan tasks, Dana over capacity, month at 18 days left. Pack assembled from the three process products.",
    source: "revops-mon",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "RevOps pack",
    body: "Monday standing for Northline.\nRouting: Dana over the 8-draft cap. Proposed move: Capital Region Schools to Mike.\nHygiene: 14 orphan tasks, 3 dead sequences on closed-won.\nPacing: Dana 48 of 78, Mike 24 of 60. Westfield cannot slip.\nNothing writes until you approve each fix.",
  }),
  item("w_pc_1", RIVERSIDE, "pacing", "Month standing · 18 days left", {
    detail: "Dana 62 percent of quota. Mike 41 percent. Assumptions visible.",
    evidence: "Quota Dana 78k, closed 48k, pipeline 42k weighted 0.4. Mike quota 60k, closed 24k. Days left 18.",
    source: "pace-month",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Pacing",
    body: "Dana 48 of 78. Pipeline 42, weight 0.4, covers the gap only if Westfield phases this month.\nMike 24 of 60. Gap is the Housing Authority renewal.\nAssumption: no slip on Westfield Friday. If it slips, the month misses.",
  }),
  item("w_pl_1", RIVERSIDE, "pipeline", "Pack · Thursday pipeline meeting", {
    detail: "Stale deals, missing next steps, wrong stages.",
    evidence: "3 deals with no next step. 1 stage still Discovery after a bid walk. 2 quiet proposals past 7 days already in the queue.",
    source: "pack-thu",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Pipeline pack",
    body: "Thursday pack.\nNo next step: Westfield ISD, Housing Authority, Lab services.\nWrong stage: Plant 4 still Discovery after a quote request.\nProposed decisions: stage Plant 4 to Proposal, book Westfield Friday, skip nothing without a reason.",
  }),
  item("w_hy_1", RIVERSIDE, "hygiene", "Orphan tasks · 14", {
    detail: "Dead sequence 3. Orphan tasks 14. Stage rot 2.",
    evidence: "Sequence 'general nurture' still on 3 closed-won. Tasks with no due date 14. Stage Discovery older than 45 days: 2.",
    source: "hygiene-1",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Hygiene fixes",
    body: "Turn off general nurture on the 3 closed-won. Delete 14 tasks with no due date, or give them one. Move 2 Discovery records older than 45 days to Nurture or close them. Nothing writes until you approve.",
  }),
  item("w_cu_1", RIVERSIDE, "custom", "School-district bid calendar", {
    detail: "The process only they have. Built, not yet measured after.",
    evidence: "Discovery: they chase K-12 bid calendars by hand every Monday. Workflow drafts the Monday list from public boards.",
    source: "custom-k12",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Custom build",
    body: "Bottleneck: Monday bid calendar, done by hand.\nBuild: pull public boards, draft the list, Dana approves, then it routes.\nBaseline: 95 minutes Monday. Re-measure in 30 days.",
  }),
  item("w_ld_1", RIVERSIDE, "leadership", "Biweekly review · this Thursday", {
    detail: "The number, the hires, the one stuck deal.",
    evidence: "Agenda: pacing, Westfield, SDR seat, after-hours on or off. Last review 14 days ago.",
    source: "lead-thu",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Leadership review",
    body: "Thursday with Mike.\n1. Pacing, 18 days left.\n2. Westfield Friday, do not slip.\n3. SDR pack, hire or wait.\n4. After-hours is on. Keep it on through the school bid season.",
  }),
  item("w_in_1", RIVERSIDE, "interview", "Config v1 · who signs, who to reject", {
    detail: "Two hours with Mike and Dana, captured.",
    evidence: "Who signs: facilities, not the superintendent. Evidence: dated public bid or capital plan. Reject: residential, one-off parts with no account.",
    source: "interview-v1",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Tenant config",
    body: "Northline config v1.\nSign: facilities.\nEvidence: public dated reason.\nRunway: 90 days.\nReject: residential, and any parts order with no account record.\nApprove to freeze this version.",
  }),
  item("w_vo_1", RIVERSIDE, "voice", "Dana voice v3 · pending her approve", {
    detail: "Built from 40 sent messages. She has not approved this version.",
    evidence: "Voice artifact v3 from sent mail and transcripts. Revocable. v2 is live. v3 waiting.",
    source: "voice-dana-v3",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Voice profile",
    body: "Dana Ruiz voice v3. Shorter close. Still first name, still Northline Supply, still no dash characters. Approve to replace v2. Revoke any time.",
  }),
  item("w_bm_1", RIVERSIDE, "benchmark", "Controls / 5-rep table", {
    detail: "Anonymized. The table the playbook already uses.",
    evidence: "Industry controls, size 5 reps. Inbound book rate 0.38 vs Northline 0.22. Quiet proposal follow-up 0.71 vs 0.40.",
    source: "bench-controls-5",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Benchmark",
    body: "Controls, 5-rep companies.\nInbound that becomes a meeting: 0.38 peer, 0.22 here.\nQuiet proposal followed in 7 days: 0.71 peer, 0.40 here.\nThis is the table, not a forecast.",
  }),
  item("w_sop_1", RIVERSIDE, "sop", "How Dana sends a missed-call text", {
    detail: "Captured from the queue, not from a slide.",
    evidence: "Screen path: queue, text, edit the name, approve. Average 40 seconds. Written as procedure.",
    source: "sop-missed",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "SOP",
    body: "SOP: missed-call text.\nOpen the queue. Read the number and the owner. Edit only the name if we know it. Approve. If you skip, write why. Never send without the approve.",
  }),
  item("w_su_1", RIVERSIDE, "supplier", "VFD kit · supplier up 6 percent", {
    detail: "Price book still at last quarter. Margin impact 230 a unit.",
    evidence: "Supplier page changed 3 days ago. VFD-SP 3800 to 4030. Open quotes using 3800: 1 (Plant 4).",
    source: "price-vfd",
    amount: 230,
    ownerName: MIKE,
    channel: "none",
    subject: "Price watch",
    body: "Spare VFD kit up 6 percent at the supplier. Price book still 3,800. Plant 4 quote is live at the old number. Update the book, or honor the quote. Pick one.",
  }),
  item("w_ins_1", RIVERSIDE, "insurance", "Westfield walkthrough · cert expires in 12 days", {
    detail: "Coverage must be current before the visit.",
    evidence: "Certificate expires in 12 days. Walkthrough in 8 days. Gap would deny site access.",
    source: "ins-westfield",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Insurance gap",
    body: "Westfield requires a current certificate. Ours expires in 12 days. Visit in 8. Renew before Friday or the walkthrough cancels.",
  }),
  item("w_cl_1", RIVERSIDE, "claims", "Rebate filing · denial pattern match", {
    detail: "Last two rebate filings missed the serial block.",
    evidence: "Pattern: denial when serial numbers are blank. This draft has two blank serials. Flagged before submit.",
    source: "claim-rebate",
    amount: 1200,
    ownerName: MIKE,
    channel: "none",
    subject: "Claim check",
    body: "Rebate filing flagged. Serial numbers blank on two lines. Last two denials were this exact gap. Fill them or do not submit.",
  }),
  item("w_fi_1", RIVERSIDE, "filings", "Permit · school job, due in 9 days", {
    detail: "Building permit packet. Deadline on the calendar.",
    evidence: "Westfield campus 2. Permit due in 9 days. Packet drafted from the bid scope. Missing: site plan page 3.",
    source: "permit-westfield",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Permit packet",
    body: "Westfield campus 2 permit. Due in 9 days. Packet is ready except site plan page 3. Assign to Mike. Do not send incomplete.",
  }),
  item("w_co_1", RIVERSIDE, "consent", "Chat opt-out · block across products", {
    detail: "Riley Brooks replied STOP on chat. Must block SMS and mail too.",
    evidence: "Opt-out on chat, 2 hours ago. Contact Riley Brooks, Facilities. No consent row for SMS or email yet. Policy: one opt-out is all channels.",
    source: "consent-riley",
    amount: 0,
    ownerName: DANA,
    channel: "none",
    subject: "Consent block",
    body: "Riley Brooks opted out on chat. Apply the block to SMS and email before any product sends. Compose may still draft. Send must refuse.",
  }),
  item("w_pu_1", RIVERSIDE, "purge", "Recordings older than 18 months", {
    detail: "Retention policy. Delete with a log. Export first if requested.",
    evidence: "Policy: recordings 18 months. 22 files past that. No export request on file. Log will write file id, date, actor.",
    source: "purge-rec",
    amount: 0,
    ownerName: MIKE,
    channel: "none",
    subject: "Purge log",
    body: "22 recordings past 18 months. No export request. Approve to delete and write the log. This cannot be undone from the desk.",
  }),
];

export const harborWorks: WorkRecord[] = [
  item("hw_ah_1", HARBOR, "afterhours", "Presque Isle Foods · overnight form", {
    detail: "Form at 22:10. Classified as meeting.",
    evidence: "Overnight web form. Classified as meeting. Asked: Who should I talk to about cold storage controls. Owner Luis Ortega. Held for morning.",
    source: "pat@pifoods.example",
    amount: 15000,
    ownerName: LUIS,
    channel: "email",
    classification: "meeting",
    subject: "Your note to Meridian Instruments",
    body: "Hi Pat,\n\nThis is Luis at Meridian Instruments. We received your form after hours. You asked who to talk to about cold storage controls. I am that person. Reply with a morning or afternoon.\n\nLuis Ortega\nMeridian Instruments",
  }),
];
