/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuditIndexRouteImport } from './routes/audit.index'
import { Route as AuditIdRouteImport } from './routes/audit.$id'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskShopIdRouteImport } from './routes/desk.$shopId'
import { Route as DeskOpsRouteImport } from './routes/desk.ops'
import { Route as PlaybookIndexRouteImport } from './routes/playbook.index'
import { Route as PlaybookIdRouteImport } from './routes/playbook.$id'
import { Route as ReportShopIdRouteImport } from './routes/report.$shopId'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopBatchRouteImport } from './routes/shop.batch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditRoute,
} as any)
const AuditIdRoute = AuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuditRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskShopIdRoute = DeskShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskOpsRoute = DeskOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => DeskRoute,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookIdRoute = PlaybookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlaybookRoute,
} as any)
const ReportShopIdRoute = ReportShopIdRouteImport.update({
  id: '/report/$shopId',
  path: '/report/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBatchRoute = ShopBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/desk': typeof DeskRouteWithChildren
  '/enter': typeof EnterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/audit/$id': typeof AuditIdRoute
  '/desk/$shopId': typeof DeskShopIdRoute
  '/desk/ops': typeof DeskOpsRoute
  '/playbook/$id': typeof PlaybookIdRoute
  '/report/$shopId': typeof ReportShopIdRoute
  '/shop/batch': typeof ShopBatchRoute
  '/audit/': typeof AuditIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/enter': typeof EnterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/audit/$id': typeof AuditIdRoute
  '/desk/$shopId': typeof DeskShopIdRoute
  '/desk/ops': typeof DeskOpsRoute
  '/playbook/$id': typeof PlaybookIdRoute
  '/report/$shopId': typeof ReportShopIdRoute
  '/shop/batch': typeof ShopBatchRoute
  '/audit': typeof AuditIndexRoute
  '/desk': typeof DeskIndexRoute
  '/playbook': typeof PlaybookIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/desk': typeof DeskRouteWithChildren
  '/enter': typeof EnterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/audit/$id': typeof AuditIdRoute
  '/desk/$shopId': typeof DeskShopIdRoute
  '/desk/ops': typeof DeskOpsRoute
  '/playbook/$id': typeof PlaybookIdRoute
  '/report/$shopId': typeof ReportShopIdRoute
  '/shop/batch': typeof ShopBatchRoute
  '/audit/': typeof AuditIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/catalog'
    | '/desk'
    | '/enter'
    | '/how-it-works'
    | '/playbook'
    | '/shop'
    | '/audit/$id'
    | '/desk/$shopId'
    | '/desk/ops'
    | '/playbook/$id'
    | '/report/$shopId'
    | '/shop/batch'
    | '/audit/'
    | '/desk/'
    | '/playbook/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/enter'
    | '/how-it-works'
    | '/audit/$id'
    | '/desk/$shopId'
    | '/desk/ops'
    | '/playbook/$id'
    | '/report/$shopId'
    | '/shop/batch'
    | '/audit'
    | '/desk'
    | '/playbook'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit'
    | '/catalog'
    | '/desk'
    | '/enter'
    | '/how-it-works'
    | '/playbook'
    | '/shop'
    | '/audit/$id'
    | '/desk/$shopId'
    | '/desk/ops'
    | '/playbook/$id'
    | '/report/$shopId'
    | '/shop/batch'
    | '/audit/'
    | '/desk/'
    | '/playbook/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  DeskRoute: typeof DeskRouteWithChildren
  EnterRoute: typeof EnterRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  ReportShopIdRoute: typeof ReportShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/$id': {
      id: '/audit/$id'
      path: '/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuditIdRouteImport
      parentRoute: typeof AuditRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/$shopId': {
      id: '/desk/$shopId'
      path: '/$shopId'
      fullPath: '/desk/$shopId'
      preLoaderRoute: typeof DeskShopIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/ops': {
      id: '/desk/ops'
      path: '/ops'
      fullPath: '/desk/ops'
      preLoaderRoute: typeof DeskOpsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/$id': {
      id: '/playbook/$id'
      path: '/$id'
      fullPath: '/playbook/$id'
      preLoaderRoute: typeof PlaybookIdRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/report/$shopId': {
      id: '/report/$shopId'
      path: '/report/$shopId'
      fullPath: '/report/$shopId'
      preLoaderRoute: typeof ReportShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/batch': {
      id: '/shop/batch'
      path: '/batch'
      fullPath: '/shop/batch'
      preLoaderRoute: typeof ShopBatchRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface AuditRouteChildren {
  AuditIdRoute: typeof AuditIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditIdRoute: AuditIdRoute,
  AuditIndexRoute: AuditIndexRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

interface DeskRouteChildren {
  DeskShopIdRoute: typeof DeskShopIdRoute
  DeskOpsRoute: typeof DeskOpsRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskShopIdRoute: DeskShopIdRoute,
  DeskOpsRoute: DeskOpsRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface PlaybookRouteChildren {
  PlaybookIdRoute: typeof PlaybookIdRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookIdRoute: PlaybookIdRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

interface ShopRouteChildren {
  ShopBatchRoute: typeof ShopBatchRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopBatchRoute: ShopBatchRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRouteWithChildren,
  CatalogRoute: CatalogRoute,
  DeskRoute: DeskRouteWithChildren,
  EnterRoute: EnterRoute,
  HowItWorksRoute: HowItWorksRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  ReportShopIdRoute: ReportShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
